/**
 * Prometheus metrics.
 *
 * Hand-rolled rather than pulling in `prom-client`. The exposition format is
 * about sixty lines of text generation, and the alternative is a dependency
 * whose default metrics registry has global mutable state that behaves badly
 * under test isolation.
 *
 * What is measured is chosen from what actually pages someone at 3am: sync
 * throughput, conflict rate, upload failures, and request latency. Vanity
 * counters are omitted — every series costs cardinality in the scrape.
 */

import { prisma } from '../../db/prisma.js';

type Labels = Record<string, string>;

interface CounterState {
  help: string;
  type: 'counter' | 'gauge';
  values: Map<string, { labels: Labels; value: number }>;
}

interface HistogramState {
  help: string;
  buckets: number[];
  series: Map<string, { labels: Labels; counts: number[]; sum: number; count: number }>;
}

const counters = new Map<string, CounterState>();
const histograms = new Map<string, HistogramState>();

/** Stable key for a label set, so ordering does not create duplicate series. */
function labelKey(labels: Labels): string {
  return Object.keys(labels)
    .sort()
    .map((k) => `${k}=${labels[k]}`)
    .join(',');
}

function escapeLabel(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

function renderLabels(labels: Labels): string {
  const entries = Object.entries(labels);
  if (entries.length === 0) return '';
  return `{${entries.map(([k, v]) => `${k}="${escapeLabel(v)}"`).join(',')}}`;
}

export function defineCounter(
  name: string,
  help: string,
  type: 'counter' | 'gauge' = 'counter',
): void {
  if (!counters.has(name)) counters.set(name, { help, type, values: new Map() });
}

export function increment(name: string, labels: Labels = {}, by = 1): void {
  const counter = counters.get(name);
  if (!counter) return;
  const key = labelKey(labels);
  const existing = counter.values.get(key);
  if (existing) existing.value += by;
  else counter.values.set(key, { labels, value: by });
}

export function setGauge(name: string, value: number, labels: Labels = {}): void {
  const counter = counters.get(name);
  if (!counter) return;
  counter.values.set(labelKey(labels), { labels, value });
}

export function defineHistogram(name: string, help: string, buckets: number[]): void {
  if (!histograms.has(name)) {
    histograms.set(name, { help, buckets: [...buckets].sort((a, b) => a - b), series: new Map() });
  }
}

export function observe(name: string, value: number, labels: Labels = {}): void {
  const histogram = histograms.get(name);
  if (!histogram) return;

  const key = labelKey(labels);
  let series = histogram.series.get(key);
  if (!series) {
    series = { labels, counts: new Array(histogram.buckets.length).fill(0), sum: 0, count: 0 };
    histogram.series.set(key, series);
  }

  series.sum += value;
  series.count += 1;
  // Cumulative buckets: Prometheus histograms are "less than or equal to".
  for (let i = 0; i < histogram.buckets.length; i++) {
    if (value <= histogram.buckets[i]!) series.counts[i] = (series.counts[i] ?? 0) + 1;
  }
}

// ---------------------------------------------------------------------------
// Definitions
// ---------------------------------------------------------------------------

defineCounter('orbit_http_requests_total', 'HTTP requests by method, route, and status.');
defineCounter('orbit_http_errors_total', 'HTTP responses with a 4xx or 5xx status.');
defineCounter('orbit_sync_operations_total', 'Sync operations applied, by result.');
defineCounter('orbit_sync_conflicts_total', 'Sync conflicts raised.');
defineCounter('orbit_uploads_total', 'Chunked upload outcomes.');
defineCounter('orbit_auth_events_total', 'Authentication events by outcome.');
defineCounter('orbit_reports_generated_total', 'Reports generated by format.');
defineCounter('orbit_notifications_sent_total', 'Push notifications delivered or suppressed.');
defineCounter('orbit_emails_total', 'Emails by transport and outcome.');
defineCounter('orbit_background_jobs_total', 'Scheduled maintenance sweeps by outcome.');
defineCounter('orbit_background_job_rows_pruned_total', 'Rows removed by the maintenance sweep.');

defineCounter('orbit_build_info', 'Build metadata. Always 1.', 'gauge');
defineCounter('orbit_db_up', 'Database reachable (1) or not (0).', 'gauge');
defineCounter('orbit_redis_up', 'Redis reachable (1) or not (0).', 'gauge');
defineCounter('orbit_unresolved_conflicts', 'Conflicts awaiting a human decision.', 'gauge');
defineCounter('orbit_pending_uploads', 'Attachments queued or failed, across the fleet.', 'gauge');
defineCounter('orbit_devices_behind', 'Devices whose cursor trails the server head.', 'gauge');
defineCounter('orbit_devices_stale', 'Devices with no contact for 24 hours.', 'gauge');
defineCounter(
  'orbit_background_job_last_success_timestamp',
  'Unix time of the last successful maintenance run. Alert on staleness, not on absence — a cron that stops firing produces no failure metric at all.',
  'gauge',
);

// Latency buckets tuned to this API: most requests are indexed reads in the
// low tens of milliseconds; a sync push carrying 300 operations is seconds.
defineHistogram(
  'orbit_http_request_duration_seconds',
  'Request latency in seconds.',
  [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
);

setGauge('orbit_build_info', 1, {
  version: process.env.npm_package_version ?? '1.0.0',
  node: process.version,
});

// ---------------------------------------------------------------------------
// Collection
// ---------------------------------------------------------------------------

/**
 * Refresh gauges that describe fleet state.
 *
 * Queried at scrape time rather than maintained incrementally: these are
 * derived from the database, and a counter kept in process memory would be
 * wrong the moment a second replica exists.
 */
async function refreshGauges(): Promise<void> {
  try {
    const [conflicts, uploads, deviceRows] = await Promise.all([
      prisma.syncConflictRecord.count({ where: { resolvedAt: null } }),
      prisma.attachment.count({
        where: { deletedAt: null, state: { in: ['QUEUED', 'UPLOADING', 'FAILED'] } },
      }),
      prisma.$queryRaw<Array<{ behind: bigint; stale: bigint }>>`
        SELECT
          COUNT(*) FILTER (WHERE d."lastSyncCursor" < o."syncSequence")::bigint AS behind,
          COUNT(*) FILTER (WHERE d."lastSyncAt" IS NULL OR d."lastSyncAt" < NOW() - INTERVAL '24 hours')::bigint AS stale
        FROM devices d
        JOIN organizations o ON o.id = d."orgId"
        WHERE d."deletedAt" IS NULL AND d."revokedAt" IS NULL
      `,
    ]);

    setGauge('orbit_unresolved_conflicts', conflicts);
    setGauge('orbit_pending_uploads', uploads);
    setGauge('orbit_devices_behind', Number(deviceRows[0]?.behind ?? 0));
    setGauge('orbit_devices_stale', Number(deviceRows[0]?.stale ?? 0));
    setGauge('orbit_db_up', 1);
  } catch {
    // A scrape must always return something. Reporting the database as down is
    // more useful than a 500 that Prometheus records as a scrape failure with
    // no detail.
    setGauge('orbit_db_up', 0);
  }
}

/** Render the exposition format. */
export async function collectMetrics(): Promise<string> {
  await refreshGauges();

  const lines: string[] = [];

  for (const [name, counter] of counters) {
    lines.push(`# HELP ${name} ${counter.help}`);
    lines.push(`# TYPE ${name} ${counter.type}`);
    if (counter.values.size === 0) {
      lines.push(`${name} 0`);
      continue;
    }
    for (const { labels, value } of counter.values.values()) {
      lines.push(`${name}${renderLabels(labels)} ${value}`);
    }
  }

  for (const [name, histogram] of histograms) {
    lines.push(`# HELP ${name} ${histogram.help}`);
    lines.push(`# TYPE ${name} histogram`);
    for (const series of histogram.series.values()) {
      histogram.buckets.forEach((bucket, i) => {
        lines.push(
          `${name}_bucket${renderLabels({ ...series.labels, le: String(bucket) })} ${series.counts[i] ?? 0}`,
        );
      });
      lines.push(`${name}_bucket${renderLabels({ ...series.labels, le: '+Inf' })} ${series.count}`);
      lines.push(`${name}_sum${renderLabels(series.labels)} ${series.sum}`);
      lines.push(`${name}_count${renderLabels(series.labels)} ${series.count}`);
    }
  }

  // Process metrics an operator expects to find without a second exporter.
  const memory = process.memoryUsage();
  lines.push('# HELP orbit_process_resident_memory_bytes Resident memory.');
  lines.push('# TYPE orbit_process_resident_memory_bytes gauge');
  lines.push(`orbit_process_resident_memory_bytes ${memory.rss}`);
  lines.push('# HELP orbit_process_heap_used_bytes Heap in use.');
  lines.push('# TYPE orbit_process_heap_used_bytes gauge');
  lines.push(`orbit_process_heap_used_bytes ${memory.heapUsed}`);
  lines.push('# HELP orbit_process_uptime_seconds Seconds since start.');
  lines.push('# TYPE orbit_process_uptime_seconds gauge');
  lines.push(`orbit_process_uptime_seconds ${Math.floor(process.uptime())}`);

  return `${lines.join('\n')}\n`;
}

/**
 * Normalise a path into a route label.
 *
 * Raw paths would create one series per inspection id, which is how a metrics
 * backend runs out of memory. Identifiers collapse to `:id`.
 */
export function routeLabel(path: string): string {
  return path
    .replace(/\/[0-9A-HJKMNP-TV-Z]{26}(?=\/|$)/g, '/:id')
    .replace(/\/\d+(?=\/|$)/g, '/:n')
    .slice(0, 80);
}

export function resetMetrics(): void {
  for (const counter of counters.values()) counter.values.clear();
  for (const histogram of histograms.values()) histogram.series.clear();
}
