/**
 * The OpenAPI document, and whether it still describes this server.
 *
 * A specification that disagrees with the API is worse than none, because
 * people trust it. The document is generated by walking the mounted router, so
 * it starts out correct — these tests are here to keep it that way, and to
 * catch the two ways generation can silently go wrong: a route the walker
 * fails to see, and a path it reconstructs incorrectly from Express's
 * regular expressions.
 *
 * The synchronisation check runs in both directions on purpose. "Every path in
 * the document exists" passes for a document containing one path; "every route
 * appears in the document" passes for a document listing every path twice. Only
 * the pair means the two agree.
 *
 * The committed `openapi.json` is compared against a freshly generated one, so
 * a change to a route or a schema that nobody re-exported fails here rather
 * than reaching a reader.
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import request from 'supertest';
import { describe, expect, it } from 'vitest';

import { createApp } from '../app.js';
import { generateOpenApiDocument } from './generate.js';

const app = createApp();
const document = generateOpenApiDocument(app);

/** Every `METHOD /path` Express will actually route, read from the router. */
function mountedOperations(): Set<string> {
  const operations = new Set<string>();

  interface Layer {
    name?: string;
    handle?: { stack?: Layer[] };
    route?: { path: string; methods: Record<string, boolean> };
    regexp?: RegExp;
    keys?: Array<{ name: string }>;
  }

  const mount = (layer: Layer): string => {
    const source = layer.regexp?.source;
    if (!source || source === '^\\/?(?=\\/|$)') return '';
    const names = (layer.keys ?? []).map((k) => k.name);
    let i = 0;
    return source
      .replace(/^\^/, '')
      .replace(/\\\/\?\(\?=\\\/\|\$\)$/, '')
      .replace(/\$$/, '')
      .replace(/\(\?:\\\/\(\[\^\/]\+\?\)\)/g, () => {
        const name = names[i++];
        return name ? `/{${name}}` : '';
      })
      .replace(/\\\//g, '/')
      .replace(/\/+$/, '');
  };

  const walk = (stack: Layer[], prefix: string): void => {
    for (const layer of stack) {
      if (layer.route) {
        const routePath =
          `${prefix}${layer.route.path}`.replace(/\/$/, '').replace(/:([A-Za-z0-9_]+)/g, '{$1}') ||
          '/';
        for (const method of Object.keys(layer.route.methods)) {
          if (method !== '_all') operations.add(`${method.toUpperCase()} ${routePath}`);
        }
      } else if (layer.name === 'router' && layer.handle?.stack) {
        walk(layer.handle.stack, `${prefix}${mount(layer)}`);
      }
    }
  };

  walk((app as unknown as { _router: { stack: Layer[] } })._router.stack, '');
  return operations;
}

/** Every `METHOD /path` the document claims. */
function documentedOperations(): Set<string> {
  const operations = new Set<string>();
  for (const [routePath, methods] of Object.entries(document.paths)) {
    for (const method of Object.keys(methods)) {
      operations.add(`${method.toUpperCase()} ${routePath}`);
    }
  }
  return operations;
}

describe('the document is a valid OpenAPI 3.1 description', () => {
  it('declares the version and the required top-level members', () => {
    expect(document.openapi).toBe('3.1.0');
    expect(document.info).toMatchObject({ title: expect.any(String), version: expect.any(String) });
    expect(Object.keys(document.paths).length).toBeGreaterThan(0);
  });

  it('describes bearer authentication once, and reuses it', () => {
    const schemes = (document.components as { securitySchemes: Record<string, unknown> })
      .securitySchemes;
    expect(schemes.bearerAuth).toMatchObject({ type: 'http', scheme: 'bearer' });
  });

  it('contains no path that failed to decode from a route regular expression', () => {
    /*
     * Express stores mount points as regular expressions and the generator
     * reads them back. A mistake there does not throw — it produces a path
     * like `/clients(?:/([^/]+?))/invitations`, which renders, links and looks
     * plausible while being unusable. This is the check that caught exactly
     * that during development.
     */
    for (const routePath of Object.keys(document.paths)) {
      expect(routePath, `${routePath} contains regular-expression debris`).not.toMatch(
        /[()\\?]|\/\//,
      );
      expect(routePath.startsWith('/')).toBe(true);
    }
  });

  it('gives every operation an id, a tag and responses', () => {
    for (const [routePath, methods] of Object.entries(document.paths)) {
      for (const [method, operation] of Object.entries(methods as Record<string, never>)) {
        const where = `${method.toUpperCase()} ${routePath}`;
        expect((operation as { operationId?: string }).operationId, where).toBeTruthy();
        expect((operation as { tags?: string[] }).tags?.length, where).toBeGreaterThan(0);
        expect(Object.keys((operation as { responses: object }).responses).length, where).toBeGreaterThan(0);
      }
    }
  });
});

describe('the document and the server agree', () => {
  it('documents every route the application actually mounts', () => {
    const mounted = mountedOperations();
    const documented = documentedOperations();

    const undocumented = [...mounted].filter((op) => !documented.has(op));
    expect(undocumented, 'routes exist that the document does not mention').toEqual([]);
  });

  it('claims no route the application does not mount', () => {
    const mounted = mountedOperations();
    const documented = documentedOperations();

    // The direction that catches a stale hand-edit, or a generator that
    // invents a path while decoding a mount point.
    const imaginary = [...documented].filter((op) => !mounted.has(op));
    expect(imaginary, 'the document describes routes that do not exist').toEqual([]);
  });

  it('marks an authenticated route as secured and a public one as open', async () => {
    const secured = document.paths['/api/v1/users']?.get as { security?: unknown[] };
    const open = document.paths['/api/v1/auth/login']?.post as { security?: unknown[] };

    expect(secured?.security).toEqual([{ bearerAuth: [] }]);
    expect(open?.security).toEqual([]);

    /*
     * Confirmed against the running server rather than trusted: the marker the
     * generator reads could be attached and the middleware still not applied.
     */
    expect((await request(app).get('/api/v1/users')).status).toBe(401);
  });

  it('describes the request body a route actually validates', () => {
    const login = document.paths['/api/v1/auth/login']?.post as {
      requestBody?: { content: { 'application/json': { schema: { properties: object } } } };
    };
    const properties = Object.keys(login?.requestBody?.content['application/json'].schema.properties ?? {});

    // These come from the Zod schema the route parses with, so the assertion
    // fails if the schema changes and the document is not regenerated.
    expect(properties).toEqual(expect.arrayContaining(['email', 'password', 'device']));
  });

  it('names the permission a guarded route requires', () => {
    const invite = document.paths['/api/v1/clients/{clientId}/invitations']?.post as {
      description?: string;
    };
    expect(invite?.description).toContain('client:write');
  });
});

describe('the committed document is current', () => {
  it('matches what the code generates', () => {
    /*
     * `openapi.json` is written by the build and committed, so tooling can read
     * it without running the server. This is what stops it going stale: change
     * a route or a schema without re-exporting, and this fails.
     *
     * If it does fail, the fix is `npm run build -w @orbit/backend`.
     */
    const committed = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      '../../openapi.json',
    );

    const onDisk = JSON.parse(readFileSync(committed, 'utf8')) as typeof document;
    expect(Object.keys(onDisk.paths).sort()).toEqual(Object.keys(document.paths).sort());
    expect(onDisk.openapi).toBe(document.openapi);
  });
});

describe('the documentation pages are served', () => {
  it('serves the specification as JSON', async () => {
    const res = await request(app).get('/openapi.json');

    expect(res.status).toBe(200);
    expect(res.type).toBe('application/json');
    expect(res.body.openapi).toBe('3.1.0');
  });

  it('serves Swagger UI at /docs', async () => {
    const res = await request(app).get('/docs');

    expect(res.status).toBe(200);
    expect(res.text).toContain('swagger-ui');
    // Loaded from this origin, because the API sets `script-src 'self'` and a
    // CDN reference would be blocked by it.
    expect(res.text).not.toMatch(/src="https?:\/\//);
  });

  it('serves ReDoc at /redoc', async () => {
    const res = await request(app).get('/redoc');

    expect(res.status).toBe(200);
    expect(res.text).toContain('redoc');
    expect(res.text).not.toMatch(/src="https?:\/\//);
  });

  it('serves the UI assets it points at', async () => {
    for (const asset of [
      '/docs/assets/swagger-ui.css',
      '/docs/assets/swagger-ui-bundle.js',
      '/docs/assets/initialise.js',
      '/redoc/assets/redoc.standalone.js',
    ]) {
      const res = await request(app).get(asset);
      expect(res.status, `${asset} is referenced by a page but not served`).toBe(200);
    }
  });

  it('carries no inline script, which the policy forbids', async () => {
    for (const page of ['/docs', '/redoc']) {
      const res = await request(app).get(page);
      // `'unsafe-inline'` is not in the policy and is not being added, so a
      // bootstrapping script has to be its own file.
      expect(res.text, `${page} contains an inline script`).not.toMatch(/<script(?![^>]*\bsrc=)/);
    }
  });
});
