/**
 * The page.
 *
 * One route, one scroll. The order answers the questions a visitor arrives
 * with, in the order they ask them: what is this, what does it do, how is it
 * built, what does it look like, how do I get it, where are the docs, and
 * where else can I go.
 */
import { Architecture } from './components/Architecture';
import { Documentation } from './components/Documentation';
import { Download } from './components/Download';
import { Features } from './components/Features';
import { Footer } from './components/Footer';
import { Header } from './components/Header';
import { Hero } from './components/Hero';
import { QuickLinks } from './components/QuickLinks';
import { Screenshots } from './components/Screenshots';
import { Section } from './components/Section';

export function App() {
  return (
    <>
      {/* First stop for a keyboard, before the navigation. */}
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[60] focus:rounded-md focus:bg-signal focus:px-4 focus:py-2 focus:font-display focus:text-sm focus:font-semibold focus:text-canvas"
      >
        Skip to content
      </a>

      <div id="top" />
      <Header />

      <main id="main">
        <Hero />

        <Section
          id="features"
          label="Capabilities"
          title="Built for work that happens away from a desk"
          intro="Ten things the platform does. The first two are the ones everything else depends on."
        >
          <Features />
        </Section>

        <Section
          id="architecture"
          label="System"
          title="Three clients, one API, two stores"
          intro="Every company is a separate tenant, isolated at the query rather than by convention."
        >
          <Architecture />
        </Section>

        <Section
          id="screenshots"
          label="Interface"
          title="What it looks like in use"
          intro="Captures from the running product — the console and portal in production, the phone screens from the release build. Demo data throughout."
        >
          <Screenshots />
        </Section>

        <Section id="download" label="Android" title="Get the field app">
          <Download />
        </Section>

        <Section
          id="documentation"
          label="Reference"
          title="The API, documented from the API"
          intro="Generated by walking the running server, so it cannot describe an endpoint that does not exist."
        >
          <Documentation />
        </Section>

        <Section id="links" label="Directory" title="Everywhere this platform lives">
          <QuickLinks />
        </Section>
      </main>

      <Footer />
    </>
  );
}
